### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by amirgi73** [aryahadii/bookworm#1]
It worked great for a log time. Since a couple months ago, it won't work. 
`Traceback (most recent call last):
  File "C:\Users\*", line 6, in <module>
    fid = Fidibo.FidiboConnection(username, password)
  File "C:\Users\*", line 55, in __init__
    self._start_session(username, password)
  File "C:\Users\*", line 109, in _start_session
    user_id = self._login(session_key, username, password)
  File "C:\Users\*", line 92, in _login
    resp = loads(self._request(req))
  File "C:\Users\*", line 80, in _request
    dec = self._decrypt_response_data(resp[8:], resp[:8])
  File "C:\Users\*", line 69, in _decrypt_response_data
    dec = decryptor.decrypt(unpa)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\Crypto\Cipher\_mode_ecb.py", line 196, in decrypt
    raise ValueError("Data must be aligned to block boundary in ECB mode")
ValueError: Data must be aligned to block boundary in ECB mode`

**Comment by aliafshany** [comment]
سلام
این ریپو برای دکریپشن کتاب های این شرکت کار میکرد یعنی؟
میشه من یک راه ارتباطی با شما داشته باشم؟ ممنون میشم
